version: '3'

services:

  website:
    container_name: ${service}
    image: httpd:alpine
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${service}.rule=Host(`${domain}`)"
      #- "traefik.http.services.${service}.loadbalancer.server.port=PORT" # If the website expose another port than 80
      - "traefik.http.routers.${service}.entrypoints=websecure"
      - "traefik.http.routers.${SERVICE}.middlewares=${SERVICE}-csp"
      - "traefik.http.middlewares.${SERVICE}-csp.headers.contentSecurityPolicy=script-src 'self'; style-src 'self';"
    volumes:
      - ./data:/usr/local/apache2/htdocs/:ro
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true