[api]
  dashboard = true

#[log]
#  level = "DEBUG"

[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"
      permanent = true

  [entryPoints.websecure]
    address = ":443"
    [entryPoints.websecure.http.tls]
      certResolver = "letsencrypt"

[providers]
  [providers.docker]
    watch = true
    exposedByDefault = false
    network = "proxy-net"
  [providers.file]
    watch = true
    directory = "/configurations"

[certificatesResolvers.letsencrypt.acme]
  email = "YOUR_EMAIL_ADDRESS"
  storage = "acme.json"
  caServer = "https://acme-v02.api.letsencrypt.org/directory"
  [certificatesResolvers.letsencrypt.acme.tlsChallenge]