[http.middlewares]
  [http.middlewares.security-headers.headers]
    accessControlAllowMethods = "GET, OPTIONS, PUT"
    accessControlMaxAge = 100
    addVaryHeader = true
    hostsProxyHeaders = ["X-Forwarded-Host"]
    sslRedirect = true
    stsSeconds = 63072000
    stsIncludeSubdomains = true
    stsPreload = true
    forceSTSHeader = true
    frameDeny = true
    contentTypeNosniff = true
    browserXSSFilter = true
    referrerPolicy = "same-origin"
    permissionsPolicy = "camera=(), geolocation=(), microphone=(), payment=(), usb=(), vr=()"
    contentSecurityPolicy = "default-src 'none'; script-src 'self' https://traefik.github.io; connect-src 'self'; img-src 'self' data:; style-src 'self'; font-src 'self'; object-src 'none'; frame-ancestors 'none'; form-action 'none'; base-uri 'none';"
    [http.middlewares.security-headers.headers.customResponseHeaders]
      X-Robots-Tag = "none,noarchive,nosnippet,notranslate,noimageindex"
      Server = "Your Server Name"
    [http.middlewares.security-headers.headers.sslProxyHeaders]
      xForwardedProto = "https"