[http.middlewares]
  [http.middlewares.security-headers.headers]
    accessControlAllowMethods = "GET, OPTIONS, PUT"
    accessControlMaxAge = 100
    addVaryHeader = true
    hostsProxyHeaders = ["X-Forwarded-Host"]
    sslRedirect = true
    stsSeconds = 63072000
    stsIncludeSubdomains = true
    stsPreload = true
    forceSTSHeader = true
    frameDeny = true
    contentTypeNosniff = true
    browserXSSFilter = true
    referrerPolicy = "same-origin"
    permissionsPolicy = "camera=(), geolocation=(), microphone=(), payment=(), usb=(), vr=()"
    [http.middlewares.security-headers.headers.customResponseHeaders]
      X-Robots-Tag = "none,noarchive,nosnippet,notranslate,noimageindex"
      Server = "Your Server Name"
    [http.middlewares.security-headers.headers.sslProxyHeaders]
      xForwardedProto = "https"