[http.middlewares]
  [http.middlewares.security-headers.headers]
    accessControlAllowMethods = "GET, OPTIONS, PUT"
    accessControlMaxAge = 100
    addVaryHeader = true
    hostsProxyHeaders = ["X-Forwarded-Host"]
    sslRedirect = true
    stsSeconds = 63072000
    stsIncludeSubdomains = true
    stsPreload = true
    forceSTSHeader = true
    frameDeny = true
    contentTypeNosniff = true
    browserXSSFilter = true
    referrerPolicy = "same-origin"
    featurePolicy = "camera 'none'; geolocation 'none'; microphone 'none'; payment 'none'; usb 'none'; vr 'none';"
    [http.middlewares.security-headers.headers.customResponseHeaders]
      X-Robots-Tag = "none,noarchive,nosnippet,notranslate,noimageindex"
      Server = "Oh no, no server here :/"
    [http.middlewares.security-headers.headers.sslProxyHeaders]
      xForwardedProto = "https"